import { Header } from '@/components/shared/Header'
import type { Metadata } from 'next'
import { Zen_Kurenaido } from 'next/font/google'
import 'sanitize.css'

const inter = Zen_Kurenaido({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <Header />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
