import { Footer } from '@/components/shared/Footer'
import { Header } from '@/components/shared/Header'
import { baseFont } from '@/consts/fonts'
import type { Metadata } from 'next'
import 'sanitize.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body className={baseFont.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
