name: Lighthouse Check

on:
  pull_request:
    branches:
      - develop

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start Server
        run: npm start &
        shell: bash

      - name: Lighthouse Check
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            http://localhost:3000
          temporaryPublicStorage: true
          budgetPath: ./budget.json
          failOnBudget: true

      - name: Kill Server
        if: always()
        run: kill $(jobs -p) || true
